Edit readme
EtsuyaKato/chatspace pull request #4
Opened 2019-03-20 06:10 UTC by EtsuyaKato

Readme にマークアップで記述しました

2019-03-20 06:17 UTC, miyagit reviewed
中間テーブルの記述がありませんね。
中間テーブルの理解は初めは難しいかもしれないのでメンターに聞いて理解を深めましょう。

2019-03-24 08:49 UTC, ghost requested changes

2019-03-24 08:49 UTC, hiroki5123 commented on chat-space/README.md
> +- has_many :users, through: :members
アソシエーションが２つ足りません。
また、has_many :users, through: :membersのthroughのあとに誤りがあります。

2019-03-24 08:49 UTC, hiroki5123 commented on chat-space/README.md
> +### Association
アソシエーションが２つ足りません。
また、has_many :users, through: :membersのthroughのあとに誤りがあります。

2019-03-24 08:49 UTC, hiroki5123 commented on chat-space/README.md
> +|name|strng|null: false, foreign_key: true|
foreign_key: trueは必要ありません

2019-03-24 08:49 UTC, hiroki5123 commented on chat-space/README.md
> +|body|text|null: false, foreign_key: true|
ここも foreign_key: trueいるんでしょうか？

2019-03-24 08:59 UTC, ghost requested changes

2019-03-24 08:59 UTC, hiroki5123 commented on chat-space/README.md
> +### Association
アソシエーションが２つ足りません。

2019-03-24 08:59 UTC, hiroki5123 commented on chat-space/README.md
> +### Association
アソシエーションが１つ足りません。

2019-03-24 08:59 UTC, hiroki5123 commented on chat-space/README.md
> +|image|string|foreign_key: true|
ここにforeign_key: trueをつけている理由はなんですか？

2019-03-24 08:59 UTC, hiroki5123 commented
コメントには必ず返信をしてください。

2019-03-24 09:14 UTC, EtsuyaKato commented on chat-space/README.md
> +|image|string|foreign_key: true|
写真にテーブルはないので、不必要でした。
削除します

2019-03-24 09:19 UTC, EtsuyaKato commented on chat-space/README.md
> +|image|string|foreign_key: true|
アソシエーションの不足についてです。
usersテーブルはusers_groupsテーブルを中間テーブルとしてgroupsテーブルと繋がっており、
messageを複数持っているので、この二つだけでいいと考えています。
他に何が必要でしょうか

2019-03-25 02:12 UTC, miyagit reviewed
こちら変更点こちらだけでしょうか？

2019-03-25 02:16 UTC, EtsuyaKato commented
> こちら変更点こちらだけでしょうか？

はい

2019-03-26 01:51 UTC, EtsuyaKato commented on chat-space/README.md
> +### Association
何が足りないのかわかりません
教えてください

2019-03-26 02:08 UTC, TOMARUMARU reviewed
多対多のアソシエーションが組めていません。よく調べてから修正をお願いします

2019-03-26 02:22 UTC, EtsuyaKato commented
> 多対多のアソシエーションが組めていません。よく調べてから修正をお願いします

has_many　users_groupsが抜けていました。
それ以外に不備はありますか？

2019-03-27 12:51 UTC, TOMARUMARU commented on chat-space/README.md
> +|body|text|null: false|
画像単体でも送りたいのでnull: falseは外しましょう

2019-03-27 12:51 UTC, TOMARUMARU commented on chat-space/README.md
> +|group_name|string|null: false, foregin_key: true|
nameで大丈夫です。外部キーは不要です

2019-03-27 12:55 UTC, EtsuyaKato commented on chat-space/README.md
> +|group_name|string|null: false, foregin_key: true|
承知しました

2019-03-27 12:55 UTC, EtsuyaKato commented on chat-space/README.md
> +|body|text|null: false|
盲点でした。

2019-03-27 12:57 UTC, TOMARUMARU commented on chat-space/README.md
> +|group_name|string|null: false|
nameで大丈夫です。修正いただけましたらmergeしてください

2019-03-27 12:58 UTC, merged

2019-03-27 12:59 UTC, EtsuyaKato commented on chat-space/README.md
> +|group_name|string|null: false|
修正したので、mergeします