Make toppage
EtsuyaKato/chatspace pull request #5
Opened 2019-03-20 06:29 UTC by EtsuyaKato

2019-03-20 06:32 UTC, hzak2xx reviewed
scssは＆を使ってください。また、スクショも添付してください

2019-03-20 06:32 UTC, hirozak commented on chat-space/app/views/messages/index.html.haml
> +  %body
これより↑不要ですね

2019-03-20 06:32 UTC, hirozak commented on chat-space/config/routes.rb
> +  get '/messages' =>'messages#index'
resourcesを使ってonly indexにしましょう

2019-03-20 07:45 UTC, EtsuyaKato commented on chat-space/app/views/messages/index.html.haml
> +  %body
![ChatSpace](https://user-images.githubusercontent.com/47592531/54667383-906b2d80-4b2f-11e9-9d4b-d6652c76a3cf.jpg)

2019-03-24 06:08 UTC, yuki-uchida approved these changes
以下確認してください

2019-03-24 06:12 UTC, yuki-uchida requested changes

2019-03-24 06:12 UTC, yuki-uchida commented on chat-space/app/views/messages/index.html.haml
>    %head
こちら、headもbodyも不要です。なぜなら、Railsにおいてはapplication.html.erbのなかにそれぞれのviewが読み込まれる形になっているためです(yieldと書かれている部分です)

なので、application.html.erbに書かれている部分は不要です

2019-03-24 06:14 UTC, yuki-uchida commented
すいません、今レビュー依頼が4件くらいきたんですが、どういう状況ですか？

2019-03-24 07:08 UTC, EtsuyaKato commented
> すいません、今レビュー依頼が4件くらいきたんですが、どういう状況ですか？

直して、コミットを送ればそちらに通知が行くと思っていたのですが、行っていなかったようなので溜まってしまっていました。

2019-03-24 07:13 UTC, merged